[application]

[web.app]

# HTML title tag content
title = "deklassiert"
base_path = "deklassiert"

# include `assets` in web platform
[web.resource]
static_dir = "assets"

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
