services:
  deklassiert:
    build: .
    container_name: deklassiert
    network_mode: host
    env_file:
      - .env
    environment:
      - DIOXUS_BASE_PATH=deklassiert
    volumes:
      - ./data:/usr/local/app/data
    restart: unless-stopped